# Generated by Django 5.1.1 on 2024-10-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('field_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=50)),
                ('datatype', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('field_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=50)),
                ('datatype', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('table_name', models.CharField(max_length=50)),
                ('datatype', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('table_name', models.CharField(max_length=50)),
                ('datatype', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('field_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=50)),
                ('datatype', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
